### ISSUE TITLE
UI non-adaptive to notched screens

### ISSUE THREAD

**Issue by czynot** [gdgkolkata/DevFest-19-App#7]
Sorry for raising this issue xD, but the UI does not adapt for notched screens. Below is a screenshot of me running this app on my (ahem) Pixel 3 XL (ahem) emulator. Please look into this and correct this if possible. CC @ariG23498 

![Screenshot from 2019-09-15 19-17-10](https://user-images.githubusercontent.com/43883971/64922549-17067c00-d7ee-11e9-9700-229101afae93.png)

**Comment by ariG23498** [comment]
Hey @czynot thanks for the issue, this is a big UI bug here. We will try to solve this as soon as we can. Follow the thread for more UI issues. Here is a cake for you :cake:

**Comment by RoyARG02** [comment]
@czynot Try wrapping the body of the view/Scaffold with `SafeArea`.
